# Generated by Django 5.2.4 on 2025-09-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_devices', '0002_devicestatus_delete_devicestatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('fingerprint', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObservedCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('issuer', models.CharField(max_length=500)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('fingerprint', models.CharField(max_length=128)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObservedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=200)),
                ('mac', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('trust_status', models.CharField(default='unknown', max_length=50)),
                ('latest_fingerprint', models.CharField(blank=True, max_length=128, null=True)),
                ('info', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceStatus',
        ),
        migrations.AddField(
            model_name='observedcert',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certs', to='multi_devices.observeddevice'),
        ),
        migrations.AddField(
            model_name='connectionevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='multi_devices.observeddevice'),
        ),
    ]
