# Generated by Django 5.2.4 on 2025-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_devices', '0003_connectionevent_observedcert_observeddevice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionevent',
            old_name='timestamp',
            new_name='event_time',
        ),
        migrations.RenameField(
            model_name='observedcert',
            old_name='fingerprint',
            new_name='fingerprint_sha256',
        ),
        migrations.RenameField(
            model_name='observedcert',
            old_name='created_at',
            new_name='first_seen',
        ),
        migrations.RenameField(
            model_name='observedcert',
            old_name='valid_from',
            new_name='not_after',
        ),
        migrations.RenameField(
            model_name='observedcert',
            old_name='valid_to',
            new_name='not_before',
        ),
        migrations.RenameField(
            model_name='observeddevice',
            old_name='latest_fingerprint',
            new_name='latest_cert_fingerprint',
        ),
        migrations.RemoveField(
            model_name='observedcert',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='observeddevice',
            name='info',
        ),
        migrations.RemoveField(
            model_name='observeddevice',
            name='ip',
        ),
        migrations.AddField(
            model_name='observedcert',
            name='subject_cn',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observeddevice',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connectionevent',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectionevent',
            name='result',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='observedcert',
            name='issuer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='observedcert',
            name='serial_number',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='observeddevice',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observeddevice',
            name='mac',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='observeddevice',
            name='trust_status',
            field=models.CharField(choices=[('trusted', 'Trusted'), ('untrusted', 'Untrusted'), ('tampered', 'Tampered'), ('expired', 'Expired')], default='trusted', max_length=20),
        ),
    ]
