# Generated by Django 5.2.4 on 2026-01-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_devices', '0004_rename_timestamp_connectionevent_event_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('device', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('certificate_status', models.BooleanField(default=True)),
                ('key_status', models.BooleanField(default=True)),
                ('mtls_status', models.BooleanField(default=True)),
                ('mitm_status', models.BooleanField(default=True)),
                ('revoked', models.BooleanField(default=False)),
                ('latency', models.FloatField(null=True)),
                ('valid_from', models.DateTimeField(null=True)),
                ('valid_to', models.DateTimeField(null=True)),
                ('last_checked', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='observedcert',
            name='device',
        ),
        migrations.DeleteModel(
            name='ConnectionEvent',
        ),
        migrations.DeleteModel(
            name='ObservedCert',
        ),
        migrations.DeleteModel(
            name='ObservedDevice',
        ),
    ]
